import JSZip from "jszip";
import { ProjectResponse } from "../../../shared/types/user.types";
import {
  getPackageJson,
  VITE_CONFIG_TEMPLATE,
  TSCONFIG_TEMPLATE,
  TAILWIND_CONFIG_TEMPLATE,
  POSTCSS_CONFIG_TEMPLATE,
  CORE_BUTTON_TEMPLATE,
  CORE_HEADER_TEMPLATE,
  CORE_SIDEBAR_TEMPLATE,
  CORE_FOOTER_TEMPLATE,
} from "./exportTemplates";

export async function generateProjectZip(
  project: ProjectResponse,
): Promise<Buffer> {
  const zip = new JSZip();

  // 1. package.json & config files
  zip.file(
    "package.json",
    JSON.stringify(getPackageJson(project.name), null, 2),
  );
  zip.file("vite.config.ts", VITE_CONFIG_TEMPLATE);
  zip.file("tsconfig.json", TSCONFIG_TEMPLATE);
  zip.file("tailwind.config.js", TAILWIND_CONFIG_TEMPLATE);
  zip.file("postcss.config.js", POSTCSS_CONFIG_TEMPLATE);
  zip.file(
    "index.html",
    `<!doctype html>\n<html lang="en">\n  <head>\n    <meta charset="UTF-8" />\n    <meta name="viewport" content="width=device-width, initial-scale=1.0" />\n    <title>${project.name}</title>\n  </head>\n  <body class="bg-slate-50 text-slate-900">\n    <div id="root"></div>\n    <script type="module" src="/src/main.tsx"></script>\n  </body>\n</html>\n`,
  );
  zip.file(
    "README.md",
    `# ${project.name}\n\nGenerated by UI Builder Platform.\n\n## Getting Started\n\n\`\`\`bash\nnpm install\nnpm run dev\n\`\`\`\n\nRuns on http://localhost:5173\n`,
  );

  // 2. Source folder setup
  const src = zip.folder("src");
  if (!src) throw new Error("Failed to create src folder in ZIP");

  src.file(
    "main.tsx",
    `import React from 'react';\nimport ReactDOM from 'react-dom/client';\nimport App from './App';\nimport './index.css';\n\nReactDOM.createRoot(document.getElementById('root')!).render(\n  <React.StrictMode>\n    <App />\n  </React.StrictMode>\n);\n`,
  );
  src.file(
    "index.css",
    `@tailwind base;\n@tailwind components;\n@tailwind utilities;\n`,
  );

  // 3. Core Reusable Components
  const coreFolder = src.folder("components/Core");
  if (coreFolder) {
    coreFolder.file("Button.tsx", CORE_BUTTON_TEMPLATE);
    coreFolder.file("Header.tsx", CORE_HEADER_TEMPLATE);
    coreFolder.file("Sidebar.tsx", CORE_SIDEBAR_TEMPLATE);
    coreFolder.file("Footer.tsx", CORE_FOOTER_TEMPLATE);
  }

  // 4. Generate Page Components
  const pagesFolder = src.folder("pages");
  const routeImports: string[] = [];
  const routeElements: string[] = [];

  const hasRootPage = project.pages.some((p) => p.path === "/");
  const firstPagePath = project.pages[0]?.path || "/";

  if (!hasRootPage && project.pages.length > 0) {
    routeElements.push(
      `<Route path="/" element={<Navigate to="${firstPagePath}" replace />} />`,
    );
  }

  project.pages.forEach((page, idx) => {
    const rawName = page.name.replace(/[^a-zA-Z0-9]/g, "");
    const componentName = `Page_${rawName ? rawName : `Page${idx}`}`;
    routeImports.push(
      `import ${componentName} from './pages/${componentName}';`,
    );
    routeElements.push(
      `<Route path="${page.path}" element={<${componentName} />} />`,
    );

    const headerComp = page.components.find(
      (c) => c.componentType === "header",
    );
    const sidebarComp = page.components.find(
      (c) => c.componentType === "sidebar",
    );
    const footerComp = page.components.find(
      (c) => c.componentType === "footer",
    );
    const contentComps = page.components.filter(
      (c) =>
        c.componentType !== "header" &&
        c.componentType !== "sidebar" &&
        c.componentType !== "footer",
    );

    const renderedComponents = contentComps.map((c) => {
      const label =
        (c.props?.label as string) || (c.props?.title as string) || "Button";
      const variant = (c.props?.variant as string) || "primary";
      const x = c.position?.x ?? 50;
      const y = c.position?.y ?? 50;

      let clickHandler = "";
      const actionType = c.props?.actionType;
      const actionTarget = c.props?.actionTarget;
      if (actionType === "navigate" && actionTarget) {
        clickHandler = `onClick={() => navigate('${actionTarget}')}`;
      } else if (actionType === "url" && actionTarget) {
        clickHandler = `onClick={() => window.open('${actionTarget}', '_blank')}`;
      } else if (actionType === "alert" && actionTarget) {
        clickHandler = `onClick={() => alert('${actionTarget}')}`;
      }

      return `          <div style={{ position: 'absolute', left: '${x}px', top: '${y}px' }}>
            <Button variant="${variant}" ${clickHandler}>
              ${label}
            </Button>
          </div>`;
    });

    const pageBody =
      renderedComponents.length > 0
        ? renderedComponents.join("\n")
        : `          <div className="flex flex-col items-center justify-center h-64 text-slate-400 text-sm">
            <p>Canvas is empty.</p>
            <p className="text-xs text-slate-300 mt-1">Add components to this page in the UI Builder.</p>
          </div>`;

    const headerTag = headerComp
      ? `<Header title="${headerComp.props?.label || headerComp.props?.title || page.name}" variant="${headerComp.props?.variant || "standard"}" />`
      : `<Header title="${page.name}" />`;

    const sidebarTag = sidebarComp
      ? `<aside className="w-60 shrink-0 sticky top-0 self-stretch border-r border-slate-200 bg-white">
          <Sidebar title="${sidebarComp.props?.label || sidebarComp.props?.title || "Navigation"}" variant="${sidebarComp.props?.variant || "fixed"}">
            <div className="text-xs text-slate-500 py-1 px-2">• Overview</div>
            <div className="text-xs text-slate-500 py-1 px-2">• Analytics</div>
            <div className="text-xs text-slate-500 py-1 px-2">• Settings</div>
          </Sidebar>
        </aside>`
      : ``;

    const footerTag = footerComp
      ? `<Footer title="${footerComp.props?.label || footerComp.props?.title || `© 2026 ${project.name}. All rights reserved.`}" variant="${footerComp.props?.variant || "standard"}" />`
      : `<Footer title="© 2026 ${project.name}. All rights reserved." />`;

    const pageContent = `import React from 'react';
import { useNavigate } from 'react-router-dom';
import Button from '../components/Core/Button';
import Header from '../components/Core/Header';
import Sidebar from '../components/Core/Sidebar';
import Footer from '../components/Core/Footer';

export default function ${componentName}() {
  const navigate = useNavigate();

  return (
    <div className="min-h-screen flex flex-col bg-slate-50">
      ${headerTag}

      <div className="flex-1 flex w-full relative min-h-[500px]">
        ${sidebarTag}
        <main className="flex-1 relative p-6 w-full min-h-[500px] overflow-auto">
          <div className="relative w-full h-full min-h-[480px] bg-white rounded-xl shadow-xs border border-slate-200 p-6">
  ${pageBody}
          </div>
        </main>
      </div>

      <div className="mt-auto w-full shrink-0">
        ${footerTag}
      </div>
    </div>
  );
}
`;
    if (pagesFolder) {
      pagesFolder.file(`${componentName}.tsx`, pageContent);
    }
  });

  // 5. App.tsx routing
  const appContent = `import React from 'react';
import { BrowserRouter, Routes, Route, Navigate } from 'react-router-dom';
${routeImports.join("\n")}

export default function App() {
  return (
    <BrowserRouter>
      <Routes>
        ${routeElements.join("\n        ")}
      </Routes>
    </BrowserRouter>
  );
}
`;
  src.file("App.tsx", appContent);

  return await zip.generateAsync({ type: "nodebuffer" });
}
