import JSZip from "jszip";
import { ProjectResponse } from "../../../shared/types/user.types";

export async function generateProjectZip(
  project: ProjectResponse,
): Promise<Buffer> {
  const zip = new JSZip();

  // 1. package.json
  const packageJson = {
    name: project.name.toLowerCase().replace(/[^a-z0-9_-]/g, "-"),
    private: true,
    version: "0.1.0",
    type: "module",
    scripts: {
      dev: "vite",
      build: "tsc && vite build",
      preview: "vite preview",
    },
    dependencies: {
      react: "^18.3.1",
      "react-dom": "^18.3.1",
      "react-router-dom": "^6.23.1",
      "lucide-react": "^0.378.0",
    },
    devDependencies: {
      "@types/react": "^18.3.3",
      "@types/react-dom": "^18.3.0",
      "@vitejs/plugin-react": "^4.3.0",
      autoprefixer: "^10.4.19",
      postcss: "^8.4.38",
      tailwindcss: "^3.4.3",
      typescript: "^5.4.5",
      vite: "^5.2.11",
    },
  };
  zip.file("package.json", JSON.stringify(packageJson, null, 2));

  // 2. Configuration files
  zip.file(
    "vite.config.ts",
    `import { defineConfig } from 'vite';\nimport react from '@vitejs/plugin-react';\n\nexport default defineConfig({\n  plugins: [react()],\n});\n`,
  );

  zip.file(
    "tsconfig.json",
    JSON.stringify(
      {
        compilerOptions: {
          target: "ES2020",
          useDefineForClassFields: true,
          lib: ["ES2020", "DOM", "DOM.Iterable"],
          module: "ESNext",
          skipLibCheck: true,
          moduleResolution: "bundler",
          resolveJsonModule: true,
          isolatedModules: true,
          noEmit: true,
          jsx: "react-jsx",
          strict: true,
        },
        include: ["src"],
      },
      null,
      2,
    ),
  );

  zip.file(
    "tailwind.config.js",
    `/** @type {import('tailwindcss').Config} */\nexport default {\n  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],\n  theme: {\n    extend: {},\n  },\n  plugins: [],\n};\n`,
  );

  zip.file(
    "postcss.config.js",
    `export default {\n  plugins: {\n    tailwindcss: {},\n    autoprefixer: {},\n  },\n};\n`,
  );

  zip.file(
    "index.html",
    `<!doctype html>\n<html lang="en">\n  <head>\n    <meta charset="UTF-8" />\n    <meta name="viewport" content="width=device-width, initial-scale=1.0" />\n    <title>${project.name}</title>\n  </head>\n  <body class="bg-slate-50 text-slate-900">\n    <div id="root"></div>\n    <script type="module" src="/src/main.tsx"></script>\n  </body>\n</html>\n`,
  );

  // 3. README.md
  zip.file(
    "README.md",
    `# ${project.name}\n\nGenerated by UI Builder Platform.\n\n## Getting Started\n\n\`\`\`bash\nnpm install\nnpm run dev\n\`\`\`\n\nRuns on http://localhost:5173\n`,
  );

  // 4. Source folder
  const src = zip.folder("src");
  if (!src) throw new Error("Failed to create src folder in ZIP");

  src.file(
    "main.tsx",
    `import React from 'react';\nimport ReactDOM from 'react-dom/client';\nimport App from './App';\nimport './index.css';\n\nReactDOM.createRoot(document.getElementById('root')!).render(\n  <React.StrictMode>\n    <App />\n  </React.StrictMode>\n);\n`,
  );

  src.file(
    "index.css",
    `@tailwind base;\n@tailwind components;\n@tailwind utilities;\n`,
  );

  // 5. Core Reusable Components in Export (First-party, zero runtime platform dependencies)
  const coreFolder = src.folder("components/Core");
  if (coreFolder) {
    coreFolder.file(
      "Button.tsx",
      `import React from 'react';

interface ButtonProps extends React.ButtonHTMLAttributes<HTMLButtonElement> {
  variant?: string;
}

const VARIANTS: Record<string, string> = {
  primary: 'bg-indigo-600 text-white hover:bg-indigo-700 shadow-sm',
  secondary: 'bg-slate-200 text-slate-900 hover:bg-slate-300',
  outline: 'border border-indigo-600 text-indigo-600 hover:bg-indigo-50',
  ghost: 'text-indigo-600 hover:bg-indigo-50',
  danger: 'bg-red-600 text-white hover:bg-red-700 shadow-sm',
};

export default function Button({ variant = 'primary', className = '', children, ...rest }: ButtonProps) {
  const variantClass = VARIANTS[variant] || VARIANTS.primary;
  return (
    <button className={\`px-4 py-2 rounded-md text-sm font-medium transition-colors \${variantClass} \${className}\`} {...rest}>
      {children}
    </button>
  );
}
`,
    );

    coreFolder.file(
      "Header.tsx",
      `import React from 'react';

interface HeaderProps {
  title?: string;
  variant?: string;
  children?: React.ReactNode;
}

export default function Header({ title = 'Website', variant = 'standard', children }: HeaderProps) {
  const isDark = variant === 'dark';
  return (
    <header className={\`py-4 px-6 flex items-center justify-between border-b \${isDark ? 'bg-slate-900 border-slate-800 text-white' : 'bg-white border-slate-200 text-slate-900'}\`}>
      <div className="font-bold text-lg tracking-tight">{title}</div>
      <div className="flex items-center gap-3">{children}</div>
    </header>
  );
}
`,
    );

    coreFolder.file(
      "Sidebar.tsx",
      `import React from 'react';

interface SidebarProps {
  title?: string;
  variant?: string;
  children?: React.ReactNode;
}

export default function Sidebar({ title = 'Navigation', variant = 'fixed', children }: SidebarProps) {
  const isDark = variant === 'dark';
  return (
    <aside className={\`w-64 p-4 border rounded-lg shadow-sm \${isDark ? 'bg-slate-900 border-slate-800 text-slate-200' : 'bg-slate-50 border-slate-200 text-slate-800'}\`}>
      <div className="font-semibold text-xs uppercase tracking-wider mb-4 text-slate-400">{title}</div>
      <nav className="space-y-2">{children}</nav>
    </aside>
  );
}
`,
    );

    coreFolder.file(
      "Footer.tsx",
      `import React from 'react';

interface FooterProps {
  title?: string;
  variant?: string;
  children?: React.ReactNode;
}

export default function Footer({ title = '© 2026 SaaSify Inc.', variant = 'standard', children }: FooterProps) {
  const isDark = variant === 'dark' || variant === 'standard';
  return (
    <footer className={\`py-6 px-6 text-center border-t \${isDark ? 'bg-slate-900 border-slate-800 text-slate-400' : 'bg-white border-slate-200 text-slate-600'}\`}>
      <p className="text-xs mb-2">{title}</p>
      <div className="flex justify-center gap-4">{children}</div>
    </footer>
  );
}
`,
    );
  }

  // 6. Generate Page Components
  const pagesFolder = src.folder("pages");
  const routeImports: string[] = [];
  const routeElements: string[] = [];

  const hasRootPage = project.pages.some((p) => p.path === "/");
  const firstPagePath = project.pages[0]?.path || "/";
  const defaultRedirectPath = hasRootPage ? "/" : firstPagePath;

  // If there is no page explicitly mapped to '/', redirect root to the first defined page
  if (!hasRootPage && project.pages.length > 0) {
    routeElements.push(
      `<Route path="/" element={<Navigate to="${firstPagePath}" replace />} />`,
    );
  }

  project.pages.forEach((page, idx) => {
    const rawName = page.name.replace(/[^a-zA-Z0-9]/g, "");
    const componentName = `Page_${rawName ? rawName : `Page${idx}`}`;
    routeImports.push(
      `import ${componentName} from './pages/${componentName}';`,
    );
    routeElements.push(
      `<Route path="${page.path}" element={<${componentName} />} />`,
    );

    const renderedComponents = page.components.map((c) => {
      const label =
        (c.props?.label as string) ||
        (c.props?.title as string) ||
        (c.componentType === "button" ? "Button" : c.componentType);
      const variant = (c.props?.variant as string) || "primary";
      const actionType = (c.props?.actionType as string) || "none";
      const actionTarget = (c.props?.actionTarget as string) || "";
      const x = c.position?.x ?? 40;
      const y = c.position?.y ?? 40;

      let clickHandler = "";
      if (actionType === "navigate" && actionTarget) {
        clickHandler = `onClick={() => navigate('${actionTarget}')}`;
      } else if (actionType === "url" && actionTarget) {
        clickHandler = `onClick={() => window.open('${actionTarget}', '_blank')}`;
      } else if (actionType === "alert" && actionTarget) {
        clickHandler = `onClick={() => alert('${actionTarget}')}`;
      }

      if (c.componentType === "header") {
        return `          <div style={{ position: 'absolute', left: '${x}px', top: '${y}px', width: 'calc(100% - ${x * 2}px)', maxWidth: '900px' }}>
            <Header title="${label}" variant="${variant}" />
          </div>`;
      }

      if (c.componentType === "sidebar") {
        return `          <div style={{ position: 'absolute', left: '${x}px', top: '${y}px' }}>
            <Sidebar title="${label}" variant="${variant}" />
          </div>`;
      }

      if (c.componentType === "footer") {
        return `          <div style={{ position: 'absolute', left: '${x}px', top: '${y}px', width: 'calc(100% - ${x * 2}px)', maxWidth: '900px' }}>
            <Footer title="${label}" variant="${variant}" />
          </div>`;
      }

      return `          <div style={{ position: 'absolute', left: '${x}px', top: '${y}px' }}>
            <Button variant="${variant}" ${clickHandler}>
              ${label}
            </Button>
          </div>`;
    });

    const pageBody =
      renderedComponents.length > 0
        ? renderedComponents.join("\n")
        : `          <div className="flex flex-col items-center justify-center h-64 text-slate-400 text-sm">
            <p>Canvas is empty.</p>
            <p className="text-xs text-slate-300 mt-1">Add components to this page in the UI Builder.</p>
          </div>`;

    const pageContent = `import React from 'react';
import { useNavigate } from 'react-router-dom';
import Button from '../components/Core/Button';
import Header from '../components/Core/Header';
import Sidebar from '../components/Core/Sidebar';
import Footer from '../components/Core/Footer';

export default function ${componentName}() {
  const navigate = useNavigate();

  return (
    <div className="min-h-screen flex flex-col bg-slate-50">
      <Header title="${page.name}" />

      <main className="flex-1 relative p-8 max-w-6xl mx-auto w-full min-h-[500px]">
        <div className="relative w-full h-full min-h-[440px] bg-white rounded-xl shadow-sm border border-slate-200 p-6 overflow-hidden">
${pageBody}
        </div>
      </main>

      <Footer title="© 2026 ${project.name}. All rights reserved." />
    </div>
  );
}
`;
    if (pagesFolder) {
      pagesFolder.file(`${componentName}.tsx`, pageContent);
    }
  });

  // Catch-all route at the bottom
  if (project.pages.length > 0) {
    routeElements.push(
      `<Route path="*" element={<Navigate to="${defaultRedirectPath}" replace />} />`,
    );
  }

  // 7. App.tsx with React Router setup & v7 future flags
  src.file(
    "App.tsx",
    `import React from 'react';
import { BrowserRouter, Routes, Route, Navigate } from 'react-router-dom';
${routeImports.join("\n")}

export default function App() {
  return (
    <BrowserRouter future={{ v7_relativeSplatPath: true, v7_startTransition: true }}>
      <Routes>
        ${routeElements.join("\n        ")}
      </Routes>
    </BrowserRouter>
  );
}
`,
  );

  return zip.generateAsync({ type: "nodebuffer" });
}
